//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod account_status;
pub mod gender;
pub mod note;
pub mod note_hex_color;
pub mod note_status;
pub mod note_tag;
pub mod role;
pub mod tag;
pub mod user;
pub mod user_tag;
