//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::account_status::Entity as AccountStatus;
pub use super::gender::Entity as Gender;
pub use super::note::Entity as Note;
pub use super::note_hex_color::Entity as NoteHexColor;
pub use super::note_status::Entity as NoteStatus;
pub use super::note_tag::Entity as NoteTag;
pub use super::role::Entity as Role;
pub use super::tag::Entity as Tag;
pub use super::user::Entity as User;
pub use super::user_tag::Entity as UserTag;
